### ISSUE TITLE
Fonts and font sizes on OS X

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble-theme#3]
The fonts and font sizes need an overhaul for OS X.

We probably want to use the system font to fit in better -- unless we want to use the same Free font on all systems? @xPoke?

We probably want something like

    font-family: ".SFNSDisplay-Regular", HelveticaNeue, LucidaGrande;

for OS X. (Per http://furbo.org/2015/07/09/i-left-my-system-fonts-in-san-francisco/)

For font sizes, we probably want something like this:

http://apple.stackexchange.com/questions/20898/what-is-mac-os-x-lions-finder-font/20910#20910

For reference, right now things look like this:

![image](https://cloud.githubusercontent.com/assets/36527/8673727/14c8b528-2a39-11e5-888b-e4bd2117d7d7.png)

![image](https://cloud.githubusercontent.com/assets/36527/8673728/1a084c60-2a39-11e5-95e0-8db30fa4d6e3.png)

**Comment by mkrautz** [comment]
Assigning myself as I'm probably going to be fixing this by tinkering... :-)

**Comment by xPoke** [comment]
Go for it! But make sure any changes for OSX are in the OSX source :)
My osx vm is out of whack anyway.
This should also be tested on retina/non retina, i'm pretty sure the dpi is
drastically different. Retina takes priority obviously.
On 14 Jul 2015 16:02, "Mikkel Krautz" <notifications@github.com> wrote:
>
> Assigning myself as I'm probably going to be fixing this by tinkering...
:-)

**Comment by xPoke** [comment]
Is this now resolved after adding OSX specific font sizes?

**Comment by mkrautz** [comment]
Yes.
