### ISSUE TITLE
Torrent Information in Black is Unreadable in Mumble Dark Theme

### ISSUE THREAD

**Issue by jetrosut** [mumble-voip/mumble-theme#30]
Information like torrent name, size, status, seeds, and peers is not readable because they are written in black whereas the blackground is a very dark grey. Can you make the text some color other than black or grey? 
https://imgur.com/a/0ArnfI4

**Comment by Krzmbrzl** [comment]
Where did you find torrent information within Mumble? I don't recognize the screenshot at all (so I have no idea which UI component you are actually talking about)

**Comment by davidebeatrici** [comment]
I think he applied the theme to a BitTorrent client powered by Qt.

@jetrosut Please note that, if that's the case, this theme is specifically made with Mumble in mind. It was not tested with other applications.

**Comment by jetrosut** [comment]
@davidebeatrici Yes, it is qBittorrent.

Then I will be closing this issue as it's irrelevant.
