### ISSUE TITLE
Font color for the Mumble welcome message

### ISSUE THREAD

**Issue by Rantanen** [mumble-voip/mumble-theme#4]
The "1.3.0 Snapshot" message font color is barely visible in the snapshots:

![mumble motd](https://cloud.githubusercontent.com/assets/385385/8763408/98b1a1d0-2da2-11e5-9e9f-373faf30fbab.png)

**Comment by xPoke** [comment]
Duplicate of https://github.com/mumble-voip/mumble/issues/1748#issuecomment-121413054
Please see ongoing discussion there :)
